화면 줌인 줌아웃 기능
ddalpange/ssu-processing pull request #26
Opened 2024-05-20 12:28 UTC by JiaLee0707

#16 
화면 줌인 줌아웃 기능

- 마우스 클릭 시 줌인
- 설정한 시간이후 줌아웃(resetView)

2024-05-20 12:51 UTC, penspanic requested changes

2024-05-20 12:51 UTC, penspanic commented on Main/Main.pde
> +
임시로 주석친 것들 다시 원복해주세요~

2024-05-20 12:51 UTC, penspanic commented on Main/Main.pde
> -  postProcessManager.addGrain(new PVector(0.3, 0.6, 0.3));
여기도

2024-05-20 12:51 UTC, penspanic commented on Main/Main.pde
> +    cameraManager.zoom(new PVector(mouseX, mouseY), 2.0, 5000);
여기 테스트 용도로 줌이 들어가있는데 삭제해주시고 줌 전용 테스트씬을 만들어서 거기서 테스트해봅시다.

2024-05-23 02:13 UTC, JiaLee0707 commented on Main/Main.pde
> +
원복 완료했습니다~

2024-05-23 02:14 UTC, JiaLee0707 commented on Main/Main.pde
> +    cameraManager.zoom(new PVector(mouseX, mouseY), 2.0, 5000);
테스트씬 추가했습니다!

2024-05-23 03:40 UTC, penspanic commented on Main/Main.pde
> +
아직 안된 것 같은데 (postProcessManager.draw(); 삭제됨) 일단 머지하고 고쳐둘게요

2024-05-23 03:41 UTC, merged